---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Require checks in PR
        uses: devantler-tech/actions/aggregate-job-checks@8436c4a9e86ab75cd485e91530eb39bf9104bbeb # v10.1.4
        with:
          job-results: ""
