---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Require checks in PR
        uses: devantler-tech/actions/aggregate-job-checks@5bbb6cdb205d24231e934f4989e0a3e687b03411 # v13.0.6
        with:
          job-results: ""
