---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Require checks in PR
        uses: devantler-tech/actions/aggregate-job-checks@d72ecd5e8b680c2066a490a2b761a8913c454575 # v13.1.3
        with:
          job-results: ""
