name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@da153eb43b8333f13094abb151a48dc11e431988 # v13.7.4
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
