---
name: "TODOs"
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/actions/.github/workflows/scan-for-todo-comments.yaml@4caaa94e681a5627e8c77d2910dc51ea2ab34c5c # v10.2.4
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
