---
name: "TODOs"
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/scan-for-todo-comments.yaml@e823c1c1148f308d11f58e5b8b10246506e7a50d # v5.6.3
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
