---
name: "TODOs"
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/.github/.github/workflows/scan-for-todo-comments.yaml@74e540657860f2a53dbf2646394149268c974d47 # v6.2.3
    with:
      exclude-vendored: true
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
